---
- name: Create a directory if it does not exist
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: a+x



- name: Add proxy to docker
  become: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    content: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
    mode: a+w


- name: Reload the docker daemon
  become: yes
  systemd:
    daemon_reload: yes


- name: Restart the docker daemon
  become: yes
  service:
    name: docker
    state: restarted
   

  



