# Common vars
availability_zone: melbourne-qh2-uom
  
# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: dpan_http
    description: "Open all ports"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: dpan-1
    
  - name: dpan-2

instance_image: 215f9775-483c-4e0a-b703-d21a5c966f2e
instance_key_name: dpan-ssh-mac
instance_flavor: uom.mse.1c4g
database_IP: 172.26.134.17

dockerhub_username: 
dockerhub_password: 
dockerhub_pulling_image: jiaweiwu/test:map

couchdb_user: admin
couchdb_password: 1234
